---
title: "Centrality"
author: "Author"
date: "2025-09-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library(igraph)
```

```{r}
e <- read.csv("../data/cleaned/emission_trade_edgelist.csv", header = TRUE, as.is = TRUE, stringsAsFactors = FALSE)
```

# 2000
```{r}
y0 <- "X2000"
u_y0 <- e[, c("iso_o", "iso_d", y0)]
u_y0 <- subset(u_y0, u_y0[[y0]] > 0)
att2000 <- read.csv("../data/cleaned/attribute2000.csv", header = TRUE, as.is = TRUE, stringsAsFactors = FALSE)
un00 <- graph_from_data_frame(d = u_y0, directed = TRUE)
E(un00)$weight <- u_y0[[y0]]
is_directed(un00) 
length(E(un00)) == length(E(un00)$weight)
length(unique(V(un00)$name)) == gorder(un00)  
is.character(V(un00)$name) 
any(is.na(E(un00)$weight))     
any(!is.finite(E(un00)$weight))
length(unique(V(un00)$name))
```
```{r}
attify <- function(n_net, attr_df){
  V(n_net)$iso_o <- V(n_net)$name
  idx <- match(V(n_net)$name, attr_df$id)
  V(n_net)$country <- attr_df$country_x[idx]
  V(n_net)$LTE <- attr_df$LTE[idx]
  V(n_net)$internet <- attr_df$internet[idx]
  V(n_net)$log_gdp_pct <- attr_df$log_gdp_pct[idx]
  V(n_net)$scbooling <- attr_df$schooling[idx]
  V(n_net)$continent <- attr_df$continent[idx]
  V(n_net)$lat <- attr_df$all_cp[idx]
  V(n_net)$development <- attr_df$development[idx]
  
  return(n_net)
}

un00 <- attify(un00, att2000)
vertex_attr_names(un00)
```



```{r}
library(wdnet)
g0 <- igraph_to_wdnet(un00)
class(g0)
summary(g0)
print(g0, node.attrs = TRUE, edge.attrs = TRUE)
node_names0 <- g0$node.attr$iso_o 
outdegree0 <- centrality(g0, measure = "degree", degree.control = list(alpha = 0.8, mode = "out"))
indegree0 <- centrality(g0, measure = "degree", degree.control = list(alpha = 0.8, mode = "in"))
centrality_df0 <- data.frame(iso_o = node_names0, outdegree = outdegree0, indegree = indegree0)
head(centrality_df0)
```


# 2001
```{r}
y1 <- "X2001"   
u_y1 <- e[, c("iso_o", "iso_d", y1)]
u_y1 <- subset(u_y1, u_y1[[y1]] > 0)
att2001 <- read.csv("../data/cleaned/attribute2001.csv", header = TRUE, as.is = TRUE, stringsAsFactors = FALSE)
un01 <- graph_from_data_frame(d = u_y1, directed = TRUE)
E(un01)$weight <- u_y1[[y1]]
is_directed(un01) 
length(E(un01)) == length(E(un01)$weight)
length(unique(V(un01)$name)) == gorder(un01)  
is.character(V(un01)$name) 
any(is.na(E(un01)$weight))      
any(!is.finite(E(un01)$weight)) 
length(unique(V(un01)$name))
un01 <- attify(un01, att2001)
vertex_attr_names(un01)
```
```{r}
g1 <- igraph_to_wdnet(un01)
print(g1, node.attrs = TRUE, edge.attrs = TRUE)
node_names1 <- g1$node.attr$iso_o 
outdegree1 <- centrality(g1, measure = "degree", degree.control = list(alpha = 0.8, mode = "out"))
indegree1 <- centrality(g1, measure = "degree", degree.control = list(alpha = 0.8, mode = "in"))
centrality_df1 <- data.frame(iso_o = node_names1, outdegree = outdegree1, indegree = indegree1)
head(centrality_df1)
```








