---
title: "data"
author: "Author"
date: "2025-08-09"
output: html_document
---

`DF_TRADE.csv`: This file contains the Greenhouse Gas Footprints (GHGFP): Emissions embodied in bilateral trade from here, 
 https://data-explorer.oecd.org/?tm=DF_ICIO_GHG_TRADE_2023
Unit of measure: Tonnes of CO2-equivalent


`DF_ORGN.csv`: This file contains geographical and sectoral origins of greenhouse gas emitted in response to final domestic demand for goods and services downloaded from, https://data-explorer.oecd.org/?tm=DF_ICIO_GHG_ORGN_2023
Unit of measure: Tonnes of CO2-equivalent

`geo_cepii.csv`: Country level fixed attributes from CEPII 
`dist_cepii.csv`: Country pair level fixed attributed from CEPII

`IMF_classifiaction.xlsx`: The excel file containing country classification as 'Advanced' and 'Emerging and Developing' is generated from this IMF webpage, https://www.imf.org/en/Publications/WEO/weo-database/2025/april/groups-and-aggregates#oem

There are 25 csv files downloaded from WDI containing time varying attributes of countries from 1999 to 2023. The files were directly extracted in this folder and kept in the state as it was downloaded. 

This is produced from the raw data (BIMTS_HS2017_2D_CSV_1995_To_2023) downloaded from [OECD BIMTS database](https://data-explorer.oecd.org/vis?fs[0]=Topic%2C1%7CTrade%23TRD%23%7CTrade%20in%20goods%20and%20services%23TRD_GDS%23&pg=0&fc=Topic&bp=true&snb=24&df[ds]=dsDisseminateFinalDMZ&df[id]=DSD_BIMTS%40DF_BIMTS_HS2017_2D&df[ag]=OECD.SDD.TPS&df[vs]=1.0). This dataset is freely available, extracting it expands to six csv files,
HS17_2D_DE_1995_To_1999, HS17_2D_DE_2000_To_2004, HS17_2D_DE_2005_To_2009, HS17_2D_DE_2010_To_2014, HS17_2D_DE_2015_To_2019, and HS17_2D_DE_2020_To_2024. I have removed HS17_2D_DE_1995_To_1999 from the folder as my study starts at 2000. 
Due to huge size of the datasets, I am not pushing those to github. The 'Preparing' folder uses the unprocessed csv files downloaded from this link without altering anything or renaming the csv files.)



### Description of the csv files in the cleaned folder:


`total2000_2023.csv`: This is the cleaned dataset for total amount of non-cultural product trade produced from five csv files containing data on total amount of trade between countries from 2000 to 2023. The datasets were extracted from the same bulk file (BIMTS_HS2017_2D_CSV_1995_To_2023) with the code '_T' and then the aggregated unique and reproducible cultural goods amount was substracted from it. 

`dyads_fixed.csv`: This is a cleaned dataset produced from dist_cepii data. It records time invariant dyadic variables, like, common language, common colonizer, distance etc. 
`nodal_fixed.csv`: This is cleaned dataset produced from geo_cepii data, which has node level time invariant factors like landlockedness, primary language, continent, longitude, latitue etc. 
`fixed.csv`: This file is produced from above 2 files nestedly indexing on the country pairs and records all time invariants factors for both dyadic and nodal level. This will be used in the gravity equation estimation. 
`rta_long.csv`: This is the dyad level RTA dataset in the long format.

`total_edgelist.csv`: This is an edgelist created from `total2000_2023.csv`.



`distance_edgelist.csv`: This is dyadic distance edgelist created from `fixed.csv`.
`contiguity_edgelisst.csv`: This is dyadic contiguity edgelist created from `fixed.csv`.
`comcol_edgelist.csv`: This is dyadic common language edgelist created from `fixed.csv`.
`language_edgelist.csv`: This is dyadic language edgelist created from `fixed.csv`.
`rta_edgelist.csv`: This is dyadic level time variant edgelist created from `rta_long.csv`.
`panel_complete.csv`: This is the balanced panel dataset contaning all dyad level and node level values both fixed and over time for PPML estimation.

`attributeYEAR.csv': There are 24 files like this name. These are the time varying nodal attributes merged on the fixed attributes created for node attributes of the network objects.
`attributes2000_2023.csv`: This is the time series node attributes data in the long format used to build the panel dataset.
`attribute_centrality_long`: This is a csv file that contains the attribute dataset added with the network centralities of the countries over time.


`network_metrics_uniqueYEAR.csv`: There are 24 csv files for 24 years with centrality measures of the countries for unique cultural goods.
`network_metrics_reproducibleYEAR.csv`: There are 24 csv files for 24 years with centrality measures of the countries for reproducible cultural goods.
`network_metrics_totalYEAR.csv`: There are 24 csv files for 24 years with centrality measures of the countries for total goods.
`network_metrics_timeseries_unique.csv`: This is the global clustering coeffcient and average local clustering coefficients of the unique cultural goods    network over time.
`network_metrics_timeseries_reproducible.csv`: This is the global clustering coeffcient and average local clustering coefficients of the reproducible cultural goods network over time.
`network_metrics_timeseries_total.csv`: This is the global clustering coeffcient and average local clustering coefficients of all goods network over time.

`centralities_mean_timeseries_unique.csv`: mean centralities for unique cultural goods network over time.
`centralities_mean_timeseries_reproducible.csv`: mean centralities for reproducible cultural goods network over time.
`centralities_mean_timeseries_total.csv`: mean centralities of all goods network over time.
`centralities_std_timeseries_unique.csv`: Standard deviation of centralities for unique cultural goods network over time.
`centralities_std_timeseries_reproducible.csv`: Standard deviation of centralities for reproducible cultural goods network over time.
`centralities_std_timeseries_total.csv`: Standard deviation of centralities of all goods network over time.



